// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/entities.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Figure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        int32                  `protobuf:"varint,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	PieceColor    string                 `protobuf:"bytes,3,opt,name=piece_color,json=pieceColor,proto3" json:"piece_color,omitempty"`
	GameColor     string                 `protobuf:"bytes,4,opt,name=game_color,json=gameColor,proto3" json:"game_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Figure) Reset() {
	*x = Figure{}
	mi := &file_proto_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Figure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Figure) ProtoMessage() {}

func (x *Figure) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Figure.ProtoReflect.Descriptor instead.
func (*Figure) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{0}
}

func (x *Figure) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Figure) GetSymbol() int32 {
	if x != nil {
		return x.Symbol
	}
	return 0
}

func (x *Figure) GetPieceColor() string {
	if x != nil {
		return x.PieceColor
	}
	return ""
}

func (x *Figure) GetGameColor() string {
	if x != nil {
		return x.GameColor
	}
	return ""
}

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TimeTook      int64                  `protobuf:"varint,2,opt,name=time_took,json=timeTook,proto3" json:"time_took,omitempty"`
	PositionFrom  string                 `protobuf:"bytes,3,opt,name=position_from,json=positionFrom,proto3" json:"position_from,omitempty"`
	PositionTo    string                 `protobuf:"bytes,4,opt,name=position_to,json=positionTo,proto3" json:"position_to,omitempty"`
	Figure        int32                  `protobuf:"varint,5,opt,name=figure,proto3" json:"figure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_proto_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{1}
}

func (x *Move) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Move) GetTimeTook() int64 {
	if x != nil {
		return x.TimeTook
	}
	return 0
}

func (x *Move) GetPositionFrom() string {
	if x != nil {
		return x.PositionFrom
	}
	return ""
}

func (x *Move) GetPositionTo() string {
	if x != nil {
		return x.PositionTo
	}
	return ""
}

func (x *Move) GetFigure() int32 {
	if x != nil {
		return x.Figure
	}
	return 0
}

type CreatePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FiguresColor  string                 `protobuf:"bytes,2,opt,name=figures_color,json=figuresColor,proto3" json:"figures_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlayerRequest) Reset() {
	*x = CreatePlayerRequest{}
	mi := &file_proto_entities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerRequest) ProtoMessage() {}

func (x *CreatePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerRequest.ProtoReflect.Descriptor instead.
func (*CreatePlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePlayerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlayerRequest) GetFiguresColor() string {
	if x != nil {
		return x.FiguresColor
	}
	return ""
}

type UpdatePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FiguresColor  string                 `protobuf:"bytes,3,opt,name=figures_color,json=figuresColor,proto3" json:"figures_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerRequest) Reset() {
	*x = UpdatePlayerRequest{}
	mi := &file_proto_entities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerRequest) ProtoMessage() {}

func (x *UpdatePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePlayerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePlayerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePlayerRequest) GetFiguresColor() string {
	if x != nil {
		return x.FiguresColor
	}
	return ""
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FiguresColor  string                 `protobuf:"bytes,3,opt,name=figures_color,json=figuresColor,proto3" json:"figures_color,omitempty"`
	FiguresTook   []*Figure              `protobuf:"bytes,4,rep,name=figures_took,json=figuresTook,proto3" json:"figures_took,omitempty"`
	Moves         []*Move                `protobuf:"bytes,5,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_proto_entities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{4}
}

func (x *Player) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetFiguresColor() string {
	if x != nil {
		return x.FiguresColor
	}
	return ""
}

func (x *Player) GetFiguresTook() []*Figure {
	if x != nil {
		return x.FiguresTook
	}
	return nil
}

func (x *Player) GetMoves() []*Move {
	if x != nil {
		return x.Moves
	}
	return nil
}

type PlayersList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*Player              `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayersList) Reset() {
	*x = PlayersList{}
	mi := &file_proto_entities_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayersList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayersList) ProtoMessage() {}

func (x *PlayersList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayersList.ProtoReflect.Descriptor instead.
func (*PlayersList) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{5}
}

func (x *PlayersList) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type PlayerById struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerById) Reset() {
	*x = PlayerById{}
	mi := &file_proto_entities_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerById) ProtoMessage() {}

func (x *PlayerById) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerById.ProtoReflect.Descriptor instead.
func (*PlayerById) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerById) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Добавили Request в название сообщения
type CreateFigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        int32                  `protobuf:"varint,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	PieceColor    string                 `protobuf:"bytes,2,opt,name=piece_color,json=pieceColor,proto3" json:"piece_color,omitempty"`
	GameColor     string                 `protobuf:"bytes,3,opt,name=game_color,json=gameColor,proto3" json:"game_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFigureRequest) Reset() {
	*x = CreateFigureRequest{}
	mi := &file_proto_entities_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFigureRequest) ProtoMessage() {}

func (x *CreateFigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFigureRequest.ProtoReflect.Descriptor instead.
func (*CreateFigureRequest) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{7}
}

func (x *CreateFigureRequest) GetSymbol() int32 {
	if x != nil {
		return x.Symbol
	}
	return 0
}

func (x *CreateFigureRequest) GetPieceColor() string {
	if x != nil {
		return x.PieceColor
	}
	return ""
}

func (x *CreateFigureRequest) GetGameColor() string {
	if x != nil {
		return x.GameColor
	}
	return ""
}

// Добавили Request в название сообщения
type UpdateFigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        int32                  `protobuf:"varint,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	PieceColor    string                 `protobuf:"bytes,3,opt,name=piece_color,json=pieceColor,proto3" json:"piece_color,omitempty"`
	GameColor     string                 `protobuf:"bytes,4,opt,name=game_color,json=gameColor,proto3" json:"game_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFigureRequest) Reset() {
	*x = UpdateFigureRequest{}
	mi := &file_proto_entities_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFigureRequest) ProtoMessage() {}

func (x *UpdateFigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFigureRequest.ProtoReflect.Descriptor instead.
func (*UpdateFigureRequest) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateFigureRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateFigureRequest) GetSymbol() int32 {
	if x != nil {
		return x.Symbol
	}
	return 0
}

func (x *UpdateFigureRequest) GetPieceColor() string {
	if x != nil {
		return x.PieceColor
	}
	return ""
}

func (x *UpdateFigureRequest) GetGameColor() string {
	if x != nil {
		return x.GameColor
	}
	return ""
}

type FiguresList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Figures       []*Figure              `protobuf:"bytes,1,rep,name=figures,proto3" json:"figures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FiguresList) Reset() {
	*x = FiguresList{}
	mi := &file_proto_entities_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FiguresList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FiguresList) ProtoMessage() {}

func (x *FiguresList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FiguresList.ProtoReflect.Descriptor instead.
func (*FiguresList) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{9}
}

func (x *FiguresList) GetFigures() []*Figure {
	if x != nil {
		return x.Figures
	}
	return nil
}

type FigureById struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FigureById) Reset() {
	*x = FigureById{}
	mi := &file_proto_entities_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FigureById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FigureById) ProtoMessage() {}

func (x *FigureById) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FigureById.ProtoReflect.Descriptor instead.
func (*FigureById) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{10}
}

func (x *FigureById) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Добавили Request в название сообщения
type CreateMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeTook      int64                  `protobuf:"varint,1,opt,name=time_took,json=timeTook,proto3" json:"time_took,omitempty"`
	PositionFrom  string                 `protobuf:"bytes,2,opt,name=position_from,json=positionFrom,proto3" json:"position_from,omitempty"`
	PositionTo    string                 `protobuf:"bytes,3,opt,name=position_to,json=positionTo,proto3" json:"position_to,omitempty"`
	Figure        int32                  `protobuf:"varint,4,opt,name=figure,proto3" json:"figure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMoveRequest) Reset() {
	*x = CreateMoveRequest{}
	mi := &file_proto_entities_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMoveRequest) ProtoMessage() {}

func (x *CreateMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMoveRequest.ProtoReflect.Descriptor instead.
func (*CreateMoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{11}
}

func (x *CreateMoveRequest) GetTimeTook() int64 {
	if x != nil {
		return x.TimeTook
	}
	return 0
}

func (x *CreateMoveRequest) GetPositionFrom() string {
	if x != nil {
		return x.PositionFrom
	}
	return ""
}

func (x *CreateMoveRequest) GetPositionTo() string {
	if x != nil {
		return x.PositionTo
	}
	return ""
}

func (x *CreateMoveRequest) GetFigure() int32 {
	if x != nil {
		return x.Figure
	}
	return 0
}

// Добавили Request в название сообщения
type UpdateMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TimeTook      int64                  `protobuf:"varint,2,opt,name=time_took,json=timeTook,proto3" json:"time_took,omitempty"`
	PositionFrom  string                 `protobuf:"bytes,3,opt,name=position_from,json=positionFrom,proto3" json:"position_from,omitempty"`
	PositionTo    string                 `protobuf:"bytes,4,opt,name=position_to,json=positionTo,proto3" json:"position_to,omitempty"`
	Figure        int32                  `protobuf:"varint,5,opt,name=figure,proto3" json:"figure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMoveRequest) Reset() {
	*x = UpdateMoveRequest{}
	mi := &file_proto_entities_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMoveRequest) ProtoMessage() {}

func (x *UpdateMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMoveRequest.ProtoReflect.Descriptor instead.
func (*UpdateMoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateMoveRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMoveRequest) GetTimeTook() int64 {
	if x != nil {
		return x.TimeTook
	}
	return 0
}

func (x *UpdateMoveRequest) GetPositionFrom() string {
	if x != nil {
		return x.PositionFrom
	}
	return ""
}

func (x *UpdateMoveRequest) GetPositionTo() string {
	if x != nil {
		return x.PositionTo
	}
	return ""
}

func (x *UpdateMoveRequest) GetFigure() int32 {
	if x != nil {
		return x.Figure
	}
	return 0
}

type MovesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moves         []*Move                `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovesList) Reset() {
	*x = MovesList{}
	mi := &file_proto_entities_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovesList) ProtoMessage() {}

func (x *MovesList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovesList.ProtoReflect.Descriptor instead.
func (*MovesList) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{13}
}

func (x *MovesList) GetMoves() []*Move {
	if x != nil {
		return x.Moves
	}
	return nil
}

type MoveById struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveById) Reset() {
	*x = MoveById{}
	mi := &file_proto_entities_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveById) ProtoMessage() {}

func (x *MoveById) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveById.ProtoReflect.Descriptor instead.
func (*MoveById) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{14}
}

func (x *MoveById) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_entities_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{15}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_entities_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{16}
}

var File_proto_entities_proto protoreflect.FileDescriptor

const file_proto_entities_proto_rawDesc = "" +
	"\n" +
	"\x14proto/entities.proto\x12\x05proto\"p\n" +
	"\x06Figure\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\x05R\x06symbol\x12\x1f\n" +
	"\vpiece_color\x18\x03 \x01(\tR\n" +
	"pieceColor\x12\x1d\n" +
	"\n" +
	"game_color\x18\x04 \x01(\tR\tgameColor\"\x91\x01\n" +
	"\x04Move\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttime_took\x18\x02 \x01(\x03R\btimeTook\x12#\n" +
	"\rposition_from\x18\x03 \x01(\tR\fpositionFrom\x12\x1f\n" +
	"\vposition_to\x18\x04 \x01(\tR\n" +
	"positionTo\x12\x16\n" +
	"\x06figure\x18\x05 \x01(\x05R\x06figure\"N\n" +
	"\x13CreatePlayerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rfigures_color\x18\x02 \x01(\tR\ffiguresColor\"^\n" +
	"\x13UpdatePlayerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rfigures_color\x18\x03 \x01(\tR\ffiguresColor\"\xa6\x01\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rfigures_color\x18\x03 \x01(\tR\ffiguresColor\x120\n" +
	"\ffigures_took\x18\x04 \x03(\v2\r.proto.FigureR\vfiguresTook\x12!\n" +
	"\x05moves\x18\x05 \x03(\v2\v.proto.MoveR\x05moves\"6\n" +
	"\vPlayersList\x12'\n" +
	"\aplayers\x18\x01 \x03(\v2\r.proto.PlayerR\aplayers\"\x1c\n" +
	"\n" +
	"PlayerById\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"m\n" +
	"\x13CreateFigureRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\x05R\x06symbol\x12\x1f\n" +
	"\vpiece_color\x18\x02 \x01(\tR\n" +
	"pieceColor\x12\x1d\n" +
	"\n" +
	"game_color\x18\x03 \x01(\tR\tgameColor\"}\n" +
	"\x13UpdateFigureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\x05R\x06symbol\x12\x1f\n" +
	"\vpiece_color\x18\x03 \x01(\tR\n" +
	"pieceColor\x12\x1d\n" +
	"\n" +
	"game_color\x18\x04 \x01(\tR\tgameColor\"6\n" +
	"\vFiguresList\x12'\n" +
	"\afigures\x18\x01 \x03(\v2\r.proto.FigureR\afigures\"\x1c\n" +
	"\n" +
	"FigureById\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8e\x01\n" +
	"\x11CreateMoveRequest\x12\x1b\n" +
	"\ttime_took\x18\x01 \x01(\x03R\btimeTook\x12#\n" +
	"\rposition_from\x18\x02 \x01(\tR\fpositionFrom\x12\x1f\n" +
	"\vposition_to\x18\x03 \x01(\tR\n" +
	"positionTo\x12\x16\n" +
	"\x06figure\x18\x04 \x01(\x05R\x06figure\"\x9e\x01\n" +
	"\x11UpdateMoveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttime_took\x18\x02 \x01(\x03R\btimeTook\x12#\n" +
	"\rposition_from\x18\x03 \x01(\tR\fpositionFrom\x12\x1f\n" +
	"\vposition_to\x18\x04 \x01(\tR\n" +
	"positionTo\x12\x16\n" +
	"\x06figure\x18\x05 \x01(\x05R\x06figure\".\n" +
	"\tMovesList\x12!\n" +
	"\x05moves\x18\x01 \x03(\v2\v.proto.MoveR\x05moves\"\x1a\n" +
	"\bMoveById\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"$\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\a\n" +
	"\x05Empty2\xb1\x06\n" +
	"\rEntityService\x12;\n" +
	"\fCreatePlayer\x12\x1a.proto.CreatePlayerRequest\x1a\r.proto.Player\"\x00\x12;\n" +
	"\fUpdatePlayer\x12\x1a.proto.UpdatePlayerRequest\x1a\r.proto.Player\"\x00\x121\n" +
	"\vListPlayers\x12\f.proto.Empty\x1a\x12.proto.PlayersList\"\x00\x12/\n" +
	"\tGetPlayer\x12\x11.proto.PlayerById\x1a\r.proto.Player\"\x00\x124\n" +
	"\fDeletePlayer\x12\x11.proto.PlayerById\x1a\x0f.proto.Response\"\x00\x12;\n" +
	"\fCreateFigure\x12\x1a.proto.CreateFigureRequest\x1a\r.proto.Figure\"\x00\x12;\n" +
	"\fUpdateFigure\x12\x1a.proto.UpdateFigureRequest\x1a\r.proto.Figure\"\x00\x121\n" +
	"\vListFigures\x12\f.proto.Empty\x1a\x12.proto.FiguresList\"\x00\x12/\n" +
	"\tGetFigure\x12\x11.proto.FigureById\x1a\r.proto.Figure\"\x00\x124\n" +
	"\fDeleteFigure\x12\x11.proto.FigureById\x1a\x0f.proto.Response\"\x00\x125\n" +
	"\n" +
	"CreateMove\x12\x18.proto.CreateMoveRequest\x1a\v.proto.Move\"\x00\x125\n" +
	"\n" +
	"UpdateMove\x12\x18.proto.UpdateMoveRequest\x1a\v.proto.Move\"\x00\x12-\n" +
	"\tListMoves\x12\f.proto.Empty\x1a\x10.proto.MovesList\"\x00\x12)\n" +
	"\aGetMove\x12\x0f.proto.MoveById\x1a\v.proto.Move\"\x00\x120\n" +
	"\n" +
	"DeleteMove\x12\x0f.proto.MoveById\x1a\x0f.proto.Response\"\x00B\x16Z\x14go-basic/proto;protob\x06proto3"

var (
	file_proto_entities_proto_rawDescOnce sync.Once
	file_proto_entities_proto_rawDescData []byte
)

func file_proto_entities_proto_rawDescGZIP() []byte {
	file_proto_entities_proto_rawDescOnce.Do(func() {
		file_proto_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_entities_proto_rawDesc), len(file_proto_entities_proto_rawDesc)))
	})
	return file_proto_entities_proto_rawDescData
}

var file_proto_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_entities_proto_goTypes = []any{
	(*Figure)(nil),              // 0: proto.Figure
	(*Move)(nil),                // 1: proto.Move
	(*CreatePlayerRequest)(nil), // 2: proto.CreatePlayerRequest
	(*UpdatePlayerRequest)(nil), // 3: proto.UpdatePlayerRequest
	(*Player)(nil),              // 4: proto.Player
	(*PlayersList)(nil),         // 5: proto.PlayersList
	(*PlayerById)(nil),          // 6: proto.PlayerById
	(*CreateFigureRequest)(nil), // 7: proto.CreateFigureRequest
	(*UpdateFigureRequest)(nil), // 8: proto.UpdateFigureRequest
	(*FiguresList)(nil),         // 9: proto.FiguresList
	(*FigureById)(nil),          // 10: proto.FigureById
	(*CreateMoveRequest)(nil),   // 11: proto.CreateMoveRequest
	(*UpdateMoveRequest)(nil),   // 12: proto.UpdateMoveRequest
	(*MovesList)(nil),           // 13: proto.MovesList
	(*MoveById)(nil),            // 14: proto.MoveById
	(*Response)(nil),            // 15: proto.Response
	(*Empty)(nil),               // 16: proto.Empty
}
var file_proto_entities_proto_depIdxs = []int32{
	0,  // 0: proto.Player.figures_took:type_name -> proto.Figure
	1,  // 1: proto.Player.moves:type_name -> proto.Move
	4,  // 2: proto.PlayersList.players:type_name -> proto.Player
	0,  // 3: proto.FiguresList.figures:type_name -> proto.Figure
	1,  // 4: proto.MovesList.moves:type_name -> proto.Move
	2,  // 5: proto.EntityService.CreatePlayer:input_type -> proto.CreatePlayerRequest
	3,  // 6: proto.EntityService.UpdatePlayer:input_type -> proto.UpdatePlayerRequest
	16, // 7: proto.EntityService.ListPlayers:input_type -> proto.Empty
	6,  // 8: proto.EntityService.GetPlayer:input_type -> proto.PlayerById
	6,  // 9: proto.EntityService.DeletePlayer:input_type -> proto.PlayerById
	7,  // 10: proto.EntityService.CreateFigure:input_type -> proto.CreateFigureRequest
	8,  // 11: proto.EntityService.UpdateFigure:input_type -> proto.UpdateFigureRequest
	16, // 12: proto.EntityService.ListFigures:input_type -> proto.Empty
	10, // 13: proto.EntityService.GetFigure:input_type -> proto.FigureById
	10, // 14: proto.EntityService.DeleteFigure:input_type -> proto.FigureById
	11, // 15: proto.EntityService.CreateMove:input_type -> proto.CreateMoveRequest
	12, // 16: proto.EntityService.UpdateMove:input_type -> proto.UpdateMoveRequest
	16, // 17: proto.EntityService.ListMoves:input_type -> proto.Empty
	14, // 18: proto.EntityService.GetMove:input_type -> proto.MoveById
	14, // 19: proto.EntityService.DeleteMove:input_type -> proto.MoveById
	4,  // 20: proto.EntityService.CreatePlayer:output_type -> proto.Player
	4,  // 21: proto.EntityService.UpdatePlayer:output_type -> proto.Player
	5,  // 22: proto.EntityService.ListPlayers:output_type -> proto.PlayersList
	4,  // 23: proto.EntityService.GetPlayer:output_type -> proto.Player
	15, // 24: proto.EntityService.DeletePlayer:output_type -> proto.Response
	0,  // 25: proto.EntityService.CreateFigure:output_type -> proto.Figure
	0,  // 26: proto.EntityService.UpdateFigure:output_type -> proto.Figure
	9,  // 27: proto.EntityService.ListFigures:output_type -> proto.FiguresList
	0,  // 28: proto.EntityService.GetFigure:output_type -> proto.Figure
	15, // 29: proto.EntityService.DeleteFigure:output_type -> proto.Response
	1,  // 30: proto.EntityService.CreateMove:output_type -> proto.Move
	1,  // 31: proto.EntityService.UpdateMove:output_type -> proto.Move
	13, // 32: proto.EntityService.ListMoves:output_type -> proto.MovesList
	1,  // 33: proto.EntityService.GetMove:output_type -> proto.Move
	15, // 34: proto.EntityService.DeleteMove:output_type -> proto.Response
	20, // [20:35] is the sub-list for method output_type
	5,  // [5:20] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_entities_proto_init() }
func file_proto_entities_proto_init() {
	if File_proto_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_entities_proto_rawDesc), len(file_proto_entities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_entities_proto_goTypes,
		DependencyIndexes: file_proto_entities_proto_depIdxs,
		MessageInfos:      file_proto_entities_proto_msgTypes,
	}.Build()
	File_proto_entities_proto = out.File
	file_proto_entities_proto_goTypes = nil
	file_proto_entities_proto_depIdxs = nil
}
