// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/entities.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EntityService_CreatePlayer_FullMethodName = "/proto.EntityService/CreatePlayer"
	EntityService_UpdatePlayer_FullMethodName = "/proto.EntityService/UpdatePlayer"
	EntityService_ListPlayers_FullMethodName  = "/proto.EntityService/ListPlayers"
	EntityService_GetPlayer_FullMethodName    = "/proto.EntityService/GetPlayer"
	EntityService_DeletePlayer_FullMethodName = "/proto.EntityService/DeletePlayer"
	EntityService_CreateFigure_FullMethodName = "/proto.EntityService/CreateFigure"
	EntityService_UpdateFigure_FullMethodName = "/proto.EntityService/UpdateFigure"
	EntityService_ListFigures_FullMethodName  = "/proto.EntityService/ListFigures"
	EntityService_GetFigure_FullMethodName    = "/proto.EntityService/GetFigure"
	EntityService_DeleteFigure_FullMethodName = "/proto.EntityService/DeleteFigure"
	EntityService_CreateMove_FullMethodName   = "/proto.EntityService/CreateMove"
	EntityService_UpdateMove_FullMethodName   = "/proto.EntityService/UpdateMove"
	EntityService_ListMoves_FullMethodName    = "/proto.EntityService/ListMoves"
	EntityService_GetMove_FullMethodName      = "/proto.EntityService/GetMove"
	EntityService_DeleteMove_FullMethodName   = "/proto.EntityService/DeleteMove"
)

// EntityServiceClient is the client API for EntityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EntityServiceClient interface {
	CreatePlayer(ctx context.Context, in *CreatePlayerRequest, opts ...grpc.CallOption) (*Player, error)
	UpdatePlayer(ctx context.Context, in *UpdatePlayerRequest, opts ...grpc.CallOption) (*Player, error)
	ListPlayers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PlayersList, error)
	GetPlayer(ctx context.Context, in *PlayerById, opts ...grpc.CallOption) (*Player, error)
	DeletePlayer(ctx context.Context, in *PlayerById, opts ...grpc.CallOption) (*Response, error)
	CreateFigure(ctx context.Context, in *CreateFigureRequest, opts ...grpc.CallOption) (*Figure, error)
	UpdateFigure(ctx context.Context, in *UpdateFigureRequest, opts ...grpc.CallOption) (*Figure, error)
	ListFigures(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FiguresList, error)
	GetFigure(ctx context.Context, in *FigureById, opts ...grpc.CallOption) (*Figure, error)
	DeleteFigure(ctx context.Context, in *FigureById, opts ...grpc.CallOption) (*Response, error)
	CreateMove(ctx context.Context, in *CreateMoveRequest, opts ...grpc.CallOption) (*Move, error)
	UpdateMove(ctx context.Context, in *UpdateMoveRequest, opts ...grpc.CallOption) (*Move, error)
	ListMoves(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MovesList, error)
	GetMove(ctx context.Context, in *MoveById, opts ...grpc.CallOption) (*Move, error)
	DeleteMove(ctx context.Context, in *MoveById, opts ...grpc.CallOption) (*Response, error)
}

type entityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEntityServiceClient(cc grpc.ClientConnInterface) EntityServiceClient {
	return &entityServiceClient{cc}
}

func (c *entityServiceClient) CreatePlayer(ctx context.Context, in *CreatePlayerRequest, opts ...grpc.CallOption) (*Player, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Player)
	err := c.cc.Invoke(ctx, EntityService_CreatePlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) UpdatePlayer(ctx context.Context, in *UpdatePlayerRequest, opts ...grpc.CallOption) (*Player, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Player)
	err := c.cc.Invoke(ctx, EntityService_UpdatePlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) ListPlayers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PlayersList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayersList)
	err := c.cc.Invoke(ctx, EntityService_ListPlayers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) GetPlayer(ctx context.Context, in *PlayerById, opts ...grpc.CallOption) (*Player, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Player)
	err := c.cc.Invoke(ctx, EntityService_GetPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) DeletePlayer(ctx context.Context, in *PlayerById, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, EntityService_DeletePlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) CreateFigure(ctx context.Context, in *CreateFigureRequest, opts ...grpc.CallOption) (*Figure, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Figure)
	err := c.cc.Invoke(ctx, EntityService_CreateFigure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) UpdateFigure(ctx context.Context, in *UpdateFigureRequest, opts ...grpc.CallOption) (*Figure, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Figure)
	err := c.cc.Invoke(ctx, EntityService_UpdateFigure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) ListFigures(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FiguresList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FiguresList)
	err := c.cc.Invoke(ctx, EntityService_ListFigures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) GetFigure(ctx context.Context, in *FigureById, opts ...grpc.CallOption) (*Figure, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Figure)
	err := c.cc.Invoke(ctx, EntityService_GetFigure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) DeleteFigure(ctx context.Context, in *FigureById, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, EntityService_DeleteFigure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) CreateMove(ctx context.Context, in *CreateMoveRequest, opts ...grpc.CallOption) (*Move, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Move)
	err := c.cc.Invoke(ctx, EntityService_CreateMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) UpdateMove(ctx context.Context, in *UpdateMoveRequest, opts ...grpc.CallOption) (*Move, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Move)
	err := c.cc.Invoke(ctx, EntityService_UpdateMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) ListMoves(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MovesList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MovesList)
	err := c.cc.Invoke(ctx, EntityService_ListMoves_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) GetMove(ctx context.Context, in *MoveById, opts ...grpc.CallOption) (*Move, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Move)
	err := c.cc.Invoke(ctx, EntityService_GetMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) DeleteMove(ctx context.Context, in *MoveById, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, EntityService_DeleteMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntityServiceServer is the server API for EntityService service.
// All implementations must embed UnimplementedEntityServiceServer
// for forward compatibility.
type EntityServiceServer interface {
	CreatePlayer(context.Context, *CreatePlayerRequest) (*Player, error)
	UpdatePlayer(context.Context, *UpdatePlayerRequest) (*Player, error)
	ListPlayers(context.Context, *Empty) (*PlayersList, error)
	GetPlayer(context.Context, *PlayerById) (*Player, error)
	DeletePlayer(context.Context, *PlayerById) (*Response, error)
	CreateFigure(context.Context, *CreateFigureRequest) (*Figure, error)
	UpdateFigure(context.Context, *UpdateFigureRequest) (*Figure, error)
	ListFigures(context.Context, *Empty) (*FiguresList, error)
	GetFigure(context.Context, *FigureById) (*Figure, error)
	DeleteFigure(context.Context, *FigureById) (*Response, error)
	CreateMove(context.Context, *CreateMoveRequest) (*Move, error)
	UpdateMove(context.Context, *UpdateMoveRequest) (*Move, error)
	ListMoves(context.Context, *Empty) (*MovesList, error)
	GetMove(context.Context, *MoveById) (*Move, error)
	DeleteMove(context.Context, *MoveById) (*Response, error)
	mustEmbedUnimplementedEntityServiceServer()
}

// UnimplementedEntityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEntityServiceServer struct{}

func (UnimplementedEntityServiceServer) CreatePlayer(context.Context, *CreatePlayerRequest) (*Player, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlayer not implemented")
}
func (UnimplementedEntityServiceServer) UpdatePlayer(context.Context, *UpdatePlayerRequest) (*Player, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePlayer not implemented")
}
func (UnimplementedEntityServiceServer) ListPlayers(context.Context, *Empty) (*PlayersList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlayers not implemented")
}
func (UnimplementedEntityServiceServer) GetPlayer(context.Context, *PlayerById) (*Player, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayer not implemented")
}
func (UnimplementedEntityServiceServer) DeletePlayer(context.Context, *PlayerById) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePlayer not implemented")
}
func (UnimplementedEntityServiceServer) CreateFigure(context.Context, *CreateFigureRequest) (*Figure, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFigure not implemented")
}
func (UnimplementedEntityServiceServer) UpdateFigure(context.Context, *UpdateFigureRequest) (*Figure, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFigure not implemented")
}
func (UnimplementedEntityServiceServer) ListFigures(context.Context, *Empty) (*FiguresList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFigures not implemented")
}
func (UnimplementedEntityServiceServer) GetFigure(context.Context, *FigureById) (*Figure, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFigure not implemented")
}
func (UnimplementedEntityServiceServer) DeleteFigure(context.Context, *FigureById) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFigure not implemented")
}
func (UnimplementedEntityServiceServer) CreateMove(context.Context, *CreateMoveRequest) (*Move, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMove not implemented")
}
func (UnimplementedEntityServiceServer) UpdateMove(context.Context, *UpdateMoveRequest) (*Move, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMove not implemented")
}
func (UnimplementedEntityServiceServer) ListMoves(context.Context, *Empty) (*MovesList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMoves not implemented")
}
func (UnimplementedEntityServiceServer) GetMove(context.Context, *MoveById) (*Move, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMove not implemented")
}
func (UnimplementedEntityServiceServer) DeleteMove(context.Context, *MoveById) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMove not implemented")
}
func (UnimplementedEntityServiceServer) mustEmbedUnimplementedEntityServiceServer() {}
func (UnimplementedEntityServiceServer) testEmbeddedByValue()                       {}

// UnsafeEntityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntityServiceServer will
// result in compilation errors.
type UnsafeEntityServiceServer interface {
	mustEmbedUnimplementedEntityServiceServer()
}

func RegisterEntityServiceServer(s grpc.ServiceRegistrar, srv EntityServiceServer) {
	// If the following call panics, it indicates UnimplementedEntityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EntityService_ServiceDesc, srv)
}

func _EntityService_CreatePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).CreatePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityService_CreatePlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).CreatePlayer(ctx, req.(*CreatePlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_UpdatePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).UpdatePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityService_UpdatePlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).UpdatePlayer(ctx, req.(*UpdatePlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_ListPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).ListPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityService_ListPlayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).ListPlayers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_GetPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).GetPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityService_GetPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).GetPlayer(ctx, req.(*PlayerById))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_DeletePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).DeletePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityService_DeletePlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).DeletePlayer(ctx, req.(*PlayerById))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_CreateFigure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).CreateFigure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityService_CreateFigure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).CreateFigure(ctx, req.(*CreateFigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_UpdateFigure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).UpdateFigure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityService_UpdateFigure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).UpdateFigure(ctx, req.(*UpdateFigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_ListFigures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).ListFigures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityService_ListFigures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).ListFigures(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_GetFigure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FigureById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).GetFigure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityService_GetFigure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).GetFigure(ctx, req.(*FigureById))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_DeleteFigure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FigureById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).DeleteFigure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityService_DeleteFigure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).DeleteFigure(ctx, req.(*FigureById))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_CreateMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).CreateMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityService_CreateMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).CreateMove(ctx, req.(*CreateMoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_UpdateMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).UpdateMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityService_UpdateMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).UpdateMove(ctx, req.(*UpdateMoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_ListMoves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).ListMoves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityService_ListMoves_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).ListMoves(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_GetMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).GetMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityService_GetMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).GetMove(ctx, req.(*MoveById))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_DeleteMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).DeleteMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityService_DeleteMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).DeleteMove(ctx, req.(*MoveById))
	}
	return interceptor(ctx, in, info, handler)
}

// EntityService_ServiceDesc is the grpc.ServiceDesc for EntityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EntityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EntityService",
	HandlerType: (*EntityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlayer",
			Handler:    _EntityService_CreatePlayer_Handler,
		},
		{
			MethodName: "UpdatePlayer",
			Handler:    _EntityService_UpdatePlayer_Handler,
		},
		{
			MethodName: "ListPlayers",
			Handler:    _EntityService_ListPlayers_Handler,
		},
		{
			MethodName: "GetPlayer",
			Handler:    _EntityService_GetPlayer_Handler,
		},
		{
			MethodName: "DeletePlayer",
			Handler:    _EntityService_DeletePlayer_Handler,
		},
		{
			MethodName: "CreateFigure",
			Handler:    _EntityService_CreateFigure_Handler,
		},
		{
			MethodName: "UpdateFigure",
			Handler:    _EntityService_UpdateFigure_Handler,
		},
		{
			MethodName: "ListFigures",
			Handler:    _EntityService_ListFigures_Handler,
		},
		{
			MethodName: "GetFigure",
			Handler:    _EntityService_GetFigure_Handler,
		},
		{
			MethodName: "DeleteFigure",
			Handler:    _EntityService_DeleteFigure_Handler,
		},
		{
			MethodName: "CreateMove",
			Handler:    _EntityService_CreateMove_Handler,
		},
		{
			MethodName: "UpdateMove",
			Handler:    _EntityService_UpdateMove_Handler,
		},
		{
			MethodName: "ListMoves",
			Handler:    _EntityService_ListMoves_Handler,
		},
		{
			MethodName: "GetMove",
			Handler:    _EntityService_GetMove_Handler,
		},
		{
			MethodName: "DeleteMove",
			Handler:    _EntityService_DeleteMove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/entities.proto",
}
