// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/figure": {
            "post": {
                "description": "Создает новую фигуру",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "figures"
                ],
                "summary": "Создать фигуру",
                "parameters": [
                    {
                        "description": "Данные фигуры",
                        "name": "figure",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.figureDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    }
                }
            }
        },
        "/figure/{id}": {
            "get": {
                "description": "Возвращает фигуру по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "figures"
                ],
                "summary": "Получить фигуру",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID фигуры",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/example_com_go-basic_packages_internal_models_chess.Figure"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет фигуру по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "figures"
                ],
                "summary": "Обновить фигуру",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID фигуры",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новые данные",
                        "name": "figure",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.figureDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет фигуру по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "figures"
                ],
                "summary": "Удалить фигуру",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID фигуры",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    }
                }
            }
        },
        "/figures": {
            "get": {
                "description": "Возвращает все сохраненные фигуры",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "figures"
                ],
                "summary": "Список фигур",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/example_com_go-basic_packages_internal_models_chess.Figure"
                            }
                        }
                    }
                }
            }
        },
        "/game": {
            "post": {
                "description": "Создает новую шахматную партию между двумя игроками",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Новая игра",
                "parameters": [
                    {
                        "description": "Параметры новой игры",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.createGame"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    }
                }
            }
        },
        "/game/{id}": {
            "get": {
                "description": "Возвращает текущее состояние доски в JSON или HTML (зависит от Accept-заголовка)",
                "produces": [
                    "application/json",
                    "text/html"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Отображение доски",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID игры",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/game/{id}/automove": {
            "post": {
                "description": "Запускает указанное количество автоматических ходов от лица игрока",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Автоход",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID игры",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Параметры автоматических ходов",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.autoMove"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    }
                }
            }
        },
        "/game/{id}/move": {
            "post": {
                "description": "Выполняет ход указанного игрока в активной партии",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Сделать ход",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID игры",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Параметры хода",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.move"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    }
                }
            }
        },
        "/game/{id}/stop": {
            "post": {
                "description": "Останавливает партию без объявления победителя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Остановить игру",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID игры",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    }
                }
            }
        },
        "/game/{id}/surrender": {
            "post": {
                "description": "Игрок сдается, партия завершается победой соперника",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Сдаться",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID игры",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Кто сдается",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.surrender"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    }
                }
            }
        },
        "/move": {
            "post": {
                "description": "Создает новый ход в хранилище",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "moves"
                ],
                "summary": "Создать ход",
                "parameters": [
                    {
                        "description": "Данные хода",
                        "name": "move",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.moveDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    }
                }
            }
        },
        "/move/{id}": {
            "get": {
                "description": "Возвращает ход по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "moves"
                ],
                "summary": "Получить ход",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хода",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/example_com_go-basic_packages_internal_models_player.Move"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет ход по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "moves"
                ],
                "summary": "Обновить ход",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хода",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новые данные хода",
                        "name": "move",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.moveDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет ход по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "moves"
                ],
                "summary": "Удалить ход",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID хода",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    }
                }
            }
        },
        "/moves": {
            "get": {
                "description": "Возвращает все сохраненные ходы",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "moves"
                ],
                "summary": "Список ходов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/example_com_go-basic_packages_internal_models_player.Move"
                            }
                        }
                    }
                }
            }
        },
        "/player": {
            "post": {
                "description": "Создает нового игрока в хранилище",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Создать игрока",
                "parameters": [
                    {
                        "description": "Данные игрока",
                        "name": "player",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.playerDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    }
                }
            }
        },
        "/player/{id}": {
            "get": {
                "description": "Возвращает игрока по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Получить игрока",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID игрока",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/example_com_go-basic_packages_internal_models_player.Player"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет данные игрока по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Обновить игрока",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID игрока",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Обновленные данные",
                        "name": "player",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.playerDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет игрока по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Удалить игрока",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID игрока",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/packages_internal_handlers.Err"
                        }
                    }
                }
            }
        },
        "/players": {
            "get": {
                "description": "Возвращает всех сохраненных игроков",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Список игроков",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/example_com_go-basic_packages_internal_models_player.Player"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "example_com_go-basic_packages_internal_models_chess.Figure": {
            "type": "object",
            "properties": {
                "game_color": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "piece_color": {
                    "type": "string"
                },
                "symbol": {
                    "type": "integer"
                }
            }
        },
        "example_com_go-basic_packages_internal_models_player.Move": {
            "type": "object",
            "properties": {
                "figure": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "position_from": {
                    "type": "string"
                },
                "position_to": {
                    "type": "string"
                },
                "time_took": {
                    "$ref": "#/definitions/time.Duration"
                }
            }
        },
        "example_com_go-basic_packages_internal_models_player.Player": {
            "type": "object",
            "properties": {
                "figures_color": {
                    "type": "string"
                },
                "figures_took": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/example_com_go-basic_packages_internal_models_chess.Figure"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "moves": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/example_com_go-basic_packages_internal_models_player.Move"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "packages_internal_handlers.Err": {
            "type": "object",
            "properties": {
                "err": {
                    "type": "string"
                }
            }
        },
        "packages_internal_handlers.autoMove": {
            "type": "object",
            "properties": {
                "moves_amount": {
                    "type": "integer"
                },
                "player": {
                    "type": "string"
                }
            }
        },
        "packages_internal_handlers.createGame": {
            "type": "object",
            "properties": {
                "board_size": {
                    "type": "integer"
                },
                "player_one_name": {
                    "type": "string"
                },
                "player_two_name": {
                    "type": "string"
                }
            }
        },
        "packages_internal_handlers.figureDTO": {
            "type": "object",
            "required": [
                "game_color",
                "piece_color",
                "symbol"
            ],
            "properties": {
                "game_color": {
                    "type": "string"
                },
                "piece_color": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "packages_internal_handlers.move": {
            "type": "object",
            "properties": {
                "player": {
                    "type": "string"
                },
                "position_from": {
                    "type": "string"
                },
                "position_to": {
                    "type": "string"
                }
            }
        },
        "packages_internal_handlers.moveDTO": {
            "type": "object",
            "required": [
                "figure",
                "position_from",
                "position_to"
            ],
            "properties": {
                "figure": {
                    "type": "string"
                },
                "position_from": {
                    "type": "string"
                },
                "position_to": {
                    "type": "string"
                },
                "time_took": {
                    "type": "integer"
                }
            }
        },
        "packages_internal_handlers.playerDTO": {
            "type": "object",
            "required": [
                "figures_color",
                "name"
            ],
            "properties": {
                "figures_color": {
                    "type": "string"
                },
                "figures_took": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/example_com_go-basic_packages_internal_models_chess.Figure"
                    }
                },
                "moves": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/example_com_go-basic_packages_internal_models_player.Move"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "packages_internal_handlers.response": {
            "type": "object",
            "properties": {
                "game_id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "packages_internal_handlers.surrender": {
            "type": "object",
            "properties": {
                "player": {
                    "type": "string"
                }
            }
        },
        "time.Duration": {
            "type": "integer",
            "format": "int64",
            "enum": [
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000
            ],
            "x-enum-varnames": [
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Chess Game API",
	Description:      "Web API для управления шахматными партиями и сущностями (игроки, фигуры, ходы).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
